name: att-ir
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - bzip2=1.0.8=hda65f42_9
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h33c6efd_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=he0feb66_18
  - libgcc-ng=15.2.0=h69a702a_18
  - libgomp=15.2.0=he0feb66_18
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_18
  - libuuid=2.41.3=h5347b49_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0.1=pyh8b19718_0
  - python=3.10.0=h543edf9_3_cpython
  - readline=8.3=h853b02a_0
  - setuptools=82.0.0=pyh332efcf_0
  - sqlite=3.51.2=h04a0ce9_0
  - tk=8.6.13=noxft_h366c992_103
  - wheel=0.46.3=pyhd8ed1ab_0
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.4.0
      - accelerate==1.0.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - anyio==4.12.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bert-score==0.3.13
      - bitsandbytes==0.49.2
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.4
      - cycler==0.12.1
      - datasets==2.15.0
      - dill==0.3.7
      - docstring-parser==0.17.0
      - evaluate==0.4.1
      - exceptiongroup==1.3.1
      - filelock==3.24.3
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2023.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.3
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.1
      - multiprocess==0.70.15
      - networkx==3.4.2
      - nltk==3.8.1
      - numpy==1.23.1
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - pandas==2.1.0
      - pillow==12.1.1
      - propcache==0.4.1
      - psutil==7.2.2
      - pyarrow==23.0.1
      - pyarrow-hotfix==0.7
      - pygments==2.19.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2026.2.19
      - requests==2.32.5
      - responses==0.18.0
      - rich==14.3.3
      - rouge-score==0.1.2
      - safetensors==0.7.0
      - shellingham==1.5.4
      - six==1.17.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tokenizers==0.20.3
      - torch==2.10.0
      - tqdm==4.66.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - triton==3.6.0
      - trl==0.7.10
      - typeguard==4.5.1
      - typer==0.24.0
      - typer-slim==0.24.0
      - typing-extensions==4.15.0
      - tyro==1.0.6
      - tzdata==2025.3
      - urllib3==2.6.3
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /usr/local/envs/att-ir

